### ISSUE TITLE
What time-period is this going to be based in?

### ISSUE THREAD

**Issue by eboatwright** [DomWilliams0/name-needed#92]

**Comment by DomWilliams0** [comment]
No idea yet, everything I'm working on for the foreseeable future is engine-level only...that's the fun of writing a custom engine :face_with_spiral_eyes:

**Comment by eboatwright** [comment]
oh lol. I actually understand that, because usually I write a custom engine for a game, and then don't feel like finishing the game ontop of it, and go make a new engine XD
